### ISSUE TITLE
Consider making this month -> day conversion into a map

### ISSUE THREAD

**Issue by DogeThis** [J0N-C/ajax-project#14]
https://github.com/J0N-C/ajax-project/blob/81a57a715c76ea885eeb402ef220e02c4bef1c4f/js/main.js#L191-L214

This switch statement is somewhat hard to read.

Another way to express the same thing is as an explicit mapping:

```
const monthNumberToDays = { // 0 being January
 0: 31,
 1: 29,
 2, 31,
 (etc)
}
```

var numberOfDaysinMarch = monthNumberToDays[3]

Though, this opens up the question of what the numbers mean exactly. you could just keep these as string values, like

```
const monthToDays = {
  'January': 31,  // now, no confusion about 0 or whatever
  'February': 29,
  'March': 31,
  etc
}
```

And then you'd be able to read that as a human :)

**Comment by J0N-C** [comment]
Note to self: turn monthNames into array of month objects with properties name and days. ex: monthNames = [ { name: January, days: 31 }, { name: February, days: 29 } , .... ]

**Comment by J0N-C** [comment]
Deleted `checkDaysInMonth` function and `monthNames` array, added new months array with the format `[ { name: 'January', days: 31 }, { name: 'February', days: 29 } , { name: 'March', days: 31 },  .... ];` so index numbers 0-11 are still usable for identifying months. 
Example for November: 
months[10].name === 'November'; 
months[10].days = 30.`
