### ISSUE TITLE
Consider using text-transform to achieve this effect

### ISSUE THREAD

**Issue by DogeThis** [J0N-C/ajax-project#15]
https://github.com/J0N-C/ajax-project/blob/81a57a715c76ea885eeb402ef220e02c4bef1c4f/index.html#L67-L78

There's nothing wrong with capitalizing these directly, but I see it as more of a stylistic choice. 

You could use this CSS feature to achieve the same effect, and type "normally"

https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

**Comment by J0N-C** [comment]
Will keep in mind for next time!
