### ISSUE TITLE
Button movement is confusing to the user

### ISSUE THREAD

**Issue by DogeThis** [J0N-C/ajax-project#17]
UX Principle - don't move buttons when you can help it.

I am confused when after I press the New Fact button on this page...

![image](https://user-images.githubusercontent.com/3914917/140017874-9d4946ac-98c3-4d8b-9b28-0f34bd363880.png)

... it's possible to get a fact that is too long and pushes the button down a bit.

![image](https://user-images.githubusercontent.com/3914917/140017914-5923b2ef-9c29-44f6-8591-075742067e46.png)

**Comment by J0N-C** [comment]
Minimum height set for daily-fact container element.
